### ISSUE TITLE
[Proxy] Logout should disconnect from proxy

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#179]
The connectUrl is not discarded when logging out nor replaced.
Steps to reproduce:
First onboard with a connectUrl, clear cache / log out, reconnect with another url, it still connects to the first connectUrl.

**Comment by altafan** [comment]
[`disconnectProxy`](https://github.com/tdex-network/tdex-dashboard/blob/368bdad17dfcc87ed7905fb27920165a9bbb15dd/src/features/settings/settingsSlice.ts#L63) should do the job logging out. This thunk calls the `/disconnect` endpoint of the proxy so that it stops using the URL once provided with `/connect`.

**Comment by Janaka-Steph** [comment]
Clear cache and logout calls `disconnect` but doesn't forget the url

**Comment by tiero** [comment]
Seems something we should handle in frontend
