### ISSUE TITLE
Errors "expected 1 macaroon but got 0" and "expected 1 macaroon but got 2"

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-dashboard#405]
Currently on master `selectMacaroonCreds` doesn't return the macaroon when proxy is used: https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/settings/settingsSlice.ts#L206-L211
This causes error `expected 1 macaroon but got 0`.

If we always return the macaroon we will face `expected 1 macaroon but got 2` error on Tauri.

Steps to reproduce:
- User connects by pasting the connect url
- Disconnect (https://github.com/tdex-network/tdex-dashboard/blob/master/src/common/UserMenu/index.tsx#L29-L59)
- Reconnect
- See error `expected 1 macaroon but got 2`

Calling disconnect should have clean previous macaroon.

Assuming that the error is coming from here: https://github.com/tdex-network/tdex-daemon/blob/master/pkg/macaroons/service.go#L181
I tried to replace the package with a local module like explain here https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/ in order to debug, but no success I don't see my new logs.

**Comment by tiero** [comment]
cc/ @altafan

**Comment by altafan** [comment]
@Janaka-Steph @tiero During wallet creation/restoration, the dashboard listens for daemon's replies and eventually updates the stored tdexdConnectUrl [here](https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/walletUnlocker/OnboardingConfirmMnemonic.tsx#L69-L73) and [here](https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/walletUnlocker/OnboardingRestoreMnemonic.tsx#L80-L86).

The error `expected 1 macaroon, got 0` happens because after the wallet initialization the dashboard doesn't pass the macaroon to the proxy. This should be done by calling its `/connect` endpoint with the payload containing the updated connect URL.

I think what the dashboard actually misses is reacting to whenever the `tdexdConnectUrl` and update proxy connection if needed.

I don't think [`selectMacaroonsCreds`](https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/settings/settingsSlice.ts#L206-L211) needs to be changed because when the dashboard uses the proxy it just doesn't need to be aware of the macaroon and or tls cert.
